### ISSUE TITLE
MacOS Unable to communicate with nScope

### ISSUE THREAD

**Issue by sa-battle** [nLabs-nScope/nScopeAPI#15]
On MacOS 10.13.6, after following the installation instructions I get:

$ python testConnection.py
Unable to communicate with nScope
Cannot connect to nScope

The Nscope is freshly plugged in with green GND lights illuminated.

**Comment by davidjmeyer** [comment]
Do you have another program open that is connected to the nScope?

**Comment by sa-battle** [comment]
Not currently. After quitting the Nscope GUI I unplugged the NScope and have plugged it back in again. The Green GND LEDs are illuminated on the Nscope but not the 5V LEDs.

**Comment by sa-battle** [comment]
The API depends on a firmware upgrade installed by version 0.81 of the nScope App (I was still using v0.7). After running the App once, the API works.

**Comment by davidjmeyer** [comment]
Thanks for finding that. The API should provide better error messages.
