### ISSUE TITLE
soundVisualizer.py - name 'fig' is not defined

### ISSUE THREAD

**Issue by mikewarot** [nLabs-nScope/nScopeAPI#4]
Here's the error message from WinPython when I try to run the sound visualizer example.

Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
==== No Subprocess ====

> > > Traceback (most recent call last):
> > >   File "C:\nScopeAPI\python\examples\soundVisualizer.py", line 29, in <module>
> > >     ani = animation.FuncAnimation(fig, update, interval=16)
> > > NameError: name 'fig' is not defined

**Comment by davidjmeyer** [comment]
Thanks, fixed in d9309d833bc44a4a71debd64f4d2e51469e638b4
