### ISSUE TITLE
Curve drawing brakes if moving channel around

### ISSUE THREAD

**Issue by thompsan** [nLabs-nScope/nScopeAPI#5]
When viewing 2 channels the curve drawing sometimes start behaving wierd.

In my case I was viewing the ouput of P1 at the same time feeding P1 through a Vishay V2611 Optocoupler. I then feed the output of the optocoupler to channel 4 to compare the signals. The signal is inverted and the comparison is crystal clear.
![screenshot1](https://cloud.githubusercontent.com/assets/12052725/19213969/381cdbe0-8d79-11e6-866b-0f345a51efb6.png)

 But when I move the channels wierd things start to happen. In this case I moved channel 4 down closer to channel 2 and while still holding the mouse clicked I can see the effect when I hover the channel at a certain height on the graph. When I move it upp a tad it appears crystal clear again. The wierd triangles pops up at random and disappears.
![screenshot2](https://cloud.githubusercontent.com/assets/12052725/19213986/92e8890c-8d79-11e6-8f6f-ab6a3921c1f1.png)

There is nothing wrong with my circuit since the I can view the signals steady for long periods but at the exact moment I move the channel the effect would start.

Using nScope 0.7 on Fujitsu UH552 with Windows 7 Ultimate @ 64bit
 Graphics: Intel HD Graphics 4000

**Comment by davidjmeyer** [comment]
Thanks for posting. This bug has been identified and will be fixed in our upcoming release.
